### ISSUE TITLE
upgrade role, `os_path` is undefined error

### ISSUE THREAD

**Issue by heatmiser** [redhat-cop/infra.leapp#126]
When utilizing the upgrade role, `os_path` is undefined error is thrown.

"msg": "The task includes an option with an undefined variable. The error was: 'os_path' is undefined. 'os_path' is undefined\n\nThe error appears to be in '/runner/requirements_collections/ansible_collections/infra/leapp/roles/upgrade/tasks/leapp-upgrade.yml': line 25, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Start Leapp OS upgrade\n  ^ here\n",

**Comment by swapdisk** [comment]
> Since the PR was merged, when is a new package expected? The current package is broken

Right, we'll push out a release today.

**Comment by swapdisk** [comment]
Release 1.1.3 now available on Galaxy.
