### ISSUE TITLE
Latest versions not on galaxy

### ISSUE THREAD

**Issue by sean-m-sullivan** [redhat-cop/infra.leapp#135]
With the galaxy changeover there appear to be missing versions of your collection on galaxy. 
https://galaxy.ansible.com/ui/repo/published/infra/leapp/

Lastest is 1.0.1

Not sure how you want to fix it, just uploading latest, or uploading the last few releases. You should be able to do it the normal way. However if you want me to upload some versions in a particular order, let me know and I can take care of that.

**Comment by swapdisk** [comment]
Thank you @sean-m-sullivan for raising the issue and helping me figure out how to fix it. :clap: 

The missing versions are now restored on Galaxy. The root cause was related to the rollout of a major update to the Galaxy infrastructure over the weekend.
