### ISSUE TITLE
Running parse_leapp_report alone fails. result_filename undedefined

### ISSUE THREAD

**Issue by mannyci** [redhat-cop/infra.leapp#158]
Running parse_leapp_report as a seperate role fails sine the variable result_filename is undefined.

- Even though the readme of the role says default is `/var/log/leapp/leapp-report.txt`.
https://github.com/redhat-cop/infra.leapp/blob/99e6bcd7fbc8a95ab9f3c413dca26ab639440e2e/roles/parse_leapp_report/README.md?plain=1#L9
-  that is defined in `upgrade` and `analysis` role.
https://github.com/redhat-cop/infra.leapp/blob/99e6bcd7fbc8a95ab9f3c413dca26ab639440e2e/roles/analysis/vars/main.yml#L5
https://github.com/redhat-cop/infra.leapp/blob/99e6bcd7fbc8a95ab9f3c413dca26ab639440e2e/roles/upgrade/vars/main.yml#L5

**Comment by djdanielsson** [comment]
It is not intended to be run by itself
