### ISSUE TITLE
Leapp reporting schema update for infra.leapp

### ISSUE THREAD

**Issue by jeffmcutter** [redhat-cop/infra.leapp#170]
https://github.com/redhat-cop/infra.leapp/pull/169

Using reporting schema 1.2.0 `leapp --report-schema 1.2.0` may alleviate the need to parse the txt report for errors.  However it may have implications on other things that we should consider first.  Opening this issue to give this some visibility and so we can discuss.

**Comment by swapdisk** [comment]
Fixed with #216.
