### ISSUE TITLE
analysis fails with Repository rhel-7-server-extras-rpms not found

### ISSUE THREAD

**Issue by akshat87** [redhat-cop/infra.leapp#171]
When I ran the infra.leapp.analysis, it fails with below error

Repository rhel-7-server-extras-rpms not found

when I ran the subscription-manager enable repo manually, then it works.

# subscription-manager repos --enable rhel-7-server-extras-rpms
Repository 'rhel-7-server-extras-rpms' is enabled for this system.

**Comment by akshat87** [comment]
found the issue, can we add baseurl and serverurl parameter to below ?

- name: analysis-leapp | Register to leapp activation key
  community.general.redhat_subscription:
    state: present
    activationkey: "{{ satellite_activation_key_leapp }}"
    org_id: "{{ satellite_organization }}"
    force_register: true
  notify: Register to pre leapp activation key
  when:
    - leapp_upgrade_type == 'satellite'
    - satellite_organization is defined
    - satellite_activation_key_leapp is defined

**Comment by akshat87** [comment]
can we add a parameter rhsm_baseurl in above ?

**Comment by djdanielsson** [comment]
@swapdisk, @heatmiser, @jeffmcutter thoughts?

**Comment by jeffmcutter** [comment]
Trying to understand...  What is the scenario where a satellite registration with an activation key requires a base url?

**Comment by akshat87** [comment]
actually it seems to be working after I changed the leapp_upgrade_type to cdn.

**Comment by akshat87** [comment]
is it possible to reopen this ?

**Comment by djdanielsson** [comment]
yes it is @akshat87

**Comment by akshat87** [comment]
we need base url in registration since satellite is our internal satellite.

**Comment by jeffmcutter** [comment]
Hi @akshat87,

I'm still trying to understand why this would be necessary.  Satellite by it's nature is internal and not open to the public. The same is true of my own Satellite and other Satellites I have encountered, yet they do not require the base_url to be specified.  Since you are able to enable the repository, the system is successfully registered.

Is this the task that fails?  https://github.com/redhat-cop/infra.leapp/blob/main/roles/analysis/tasks/analysis-leapp.yml#L20

Can you run `subscription-manager repos` before attempting an upgrade, then after it fails, run the same again?  Can you show the full error message.  The contents of /etc/yum.repos.d/redhat.repo on the system to be upgraded might also be useful.  Feel free to change names/addresses etc. for security sake.

Thanks,
-Jeff

**Comment by akshat87** [comment]
here is the output of subscription-manager repos, I have removed some of the details for security purposes.

subscription-manager repos
+----------------------------------------------------------+
    Available Repositories in /etc/yum.repos.d/redhat.repo
+----------------------------------------------------------+
Repo ID:   rhel-server-rhscl-7-rpms
Repo Name: Red Hat Software Collections RPMs for Red Hat Enterprise Linux 7 Server
Repo URL:  https://rhn-satellite.tools.cihs.gov.on.ca/pulp/repos/its-dco/PROD/soe_rhel7_sus/content/dist/rhel/server/
           7/$releasever/$basearch/rhscl/1/os
Enabled:   0

Repo ID:   rhel-7-server-dotnet-rpms
Repo Name: dotNET on RHEL RPMs for Red Hat Enterprise Linux 7 Server
Repo URL:  https://rhn-satellite.tools.cihs.gov.on.ca/pulp/repos/its-dco/PROD/soe_rhel7_sus/content/dist/rhel/server/
           7/$releasever/$basearch/dotnet/1/os
Enabled:   0

Repo ID:   rhel-7-server-satellite-client-6-rpms
Repo Name: Red Hat Satellite Client 6 (for RHEL 7 Server) (RPMs)
Repo URL:  https://rhn-satellite.tools.cihs.gov.on.ca/pulp/repos/its-dco/PROD/soe_rhel7_sus/content/dist/rhel/server/
           7/7Server/$basearch/sat-client/6/os
Enabled:   0

Repo ID:   rhel-7-server-optional-rpms
Repo Name: Red Hat Enterprise Linux 7 Server - Optional (RPMs)
Repo URL:  https://rhn-satellite.tools.cihs.gov.on.ca/pulp/repos/its-dco/PROD/soe_rhel7_sus/content/dist/rhel/server/
           7/$releasever/$basearch/optional/os
Enabled:   0

Repo ID:   rhel-7-server-rhceph-3-tools-rpms
Repo Name: Red Hat Ceph Storage Tools 3 for Red Hat Enterprise Linux 7 Server (RPMs)
Repo URL:  https://rhn-satellite.tools.cihs.gov.on.ca/pulp/repos/its-dco/PROD/soe_rhel7_sus/content/dist/rhel/server/
           7/7Server/$basearch/rhceph-tools/3/os
Enabled:   0

Repo ID:   rhel-7-server-rpms
Repo Name: Red Hat Enterprise Linux 7 Server (RPMs)
Repo URL:  https://rhn-satellite.tools.cihs.gov.on.ca/pulp/repos/its-dco/PROD/soe_rhel7_sus/content/dist/rhel/server/
           7/$releasever/$basearch/os
Enabled:   1

Repo ID:   rh-gluster-3-client-for-rhel-7-server-rpms
Repo Name: Red Hat Storage Native Client for RHEL 7 (RPMs)
Repo URL:  https://rhn-satellite.tools.cihs.gov.on.ca/pulp/repos/its-dco/PROD/soe_rhel7_sus/content/dist/rhel/server/
           7/$releasever/$basearch/rhs-client/os
Enabled:   0

Repo ID:   rhel-7-server-rhceph-4-tools-rpms
Repo Name: Red Hat Ceph Storage Tools 4 for Red Hat Enterprise Linux 7 Server (RPMs)
Repo URL:  https://xxxx/pulp/repos/yyyy/PROD/zzzz/content/dist/rhel/server/
           7/7Server/$basearch/rhceph-tools/4/os
Enabled:   0

Repo ID:   rhel-7-server-supplementary-rpms
Repo Name: Red Hat Enterprise Linux 7 Server - Supplementary (RPMs)
Repo URL:  https://xxxx/pulp/repos/yyyy/PROD/zzzz/content/dist/rhel/server/
           7/$releasever/$basearch/supplementary/os
Enabled:   0

Repo ID:   rhel-7-server-extras-rpms
Repo Name: Red Hat Enterprise Linux 7 Server - Extras (RPMs)
Repo URL:  https://xxxx/pulp/repos/yyyy/PROD/zzzz/content/dist/rhel/server/
           7/7Server/$basearch/extras/os
Enabled:   1

Repo ID:   rhel-7-server-ansible-2.9-rpms
Repo Name: Red Hat Ansible Engine 2.9 RPMs for Red Hat Enterprise Linux 7 Server
Repo URL:  https://xxxx/pulp/repos/yyyy/PROD/zzzz/content/dist/rhel/server/
           7/7Server/$basearch/ansible/2.9/os
Enabled:   0

**Comment by jeffmcutter** [comment]
"Can you run subscription-manager repos before attempting an upgrade, then after it fails, run the same again?"

Is that before or after?  I see rhel-7-server-extras-rpm is enabled.

**Comment by akshat87** [comment]
**Before**

```
+----------------------------------------------------------+
    Available Repositories in /etc/yum.repos.d/redhat.repo
+----------------------------------------------------------+
Repo ID:   rhel-server-rhscl-7-rpms
Repo Name: Red Hat Software Collections RPMs for Red Hat Enterprise Linux 7 Server
Repo URL:  https://xxxx/pulp/repos/yyyy/DEV/zzzz/content/dist/rhel/server/7
           /$releasever/$basearch/rhscl/1/os
Enabled:   0

Repo ID:   rhel-7-server-dotnet-rpms
Repo Name: dotNET on RHEL RPMs for Red Hat Enterprise Linux 7 Server
Repo URL:  https://xxxx/pulp/repos/yyyy/DEV/zzzz/content/dist/rhel/server/7
           /$releasever/$basearch/dotnet/1/os
Enabled:   0

Repo ID:   rhel-7-server-satellite-client-6-rpms
Repo Name: Red Hat Satellite Client 6 (for RHEL 7 Server) (RPMs)
Repo URL:  https://xxxx/pulp/repos/yyyy/DEV/zzzz/content/dist/rhel/server/7
           /7Server/$basearch/sat-client/6/os
Enabled:   0

Repo ID:   yyyy_Microsoft_7Server_x86_64
Repo Name: 7Server x86_64
Repo URL:  https://xxxx/pulp/repos/yyyy/DEV/zzzz/custom/Microsoft/7Server_x
           86_64
Enabled:   1

Repo ID:   rhel-7-server-optional-rpms
Repo Name: Red Hat Enterprise Linux 7 Server - Optional (RPMs)
Repo URL:  https://xxxx/pulp/repos/yyyy/DEV/zzzz/content/dist/rhel/server/7
           /$releasever/$basearch/optional/os
Enabled:   0

Repo ID:   rhel-7-server-rhceph-3-tools-rpms
Repo Name: Red Hat Ceph Storage Tools 3 for Red Hat Enterprise Linux 7 Server (RPMs)
Repo URL:  https://xxxx/pulp/repos/yyyy/DEV/zzzz/content/dist/rhel/server/7
           /7Server/$basearch/rhceph-tools/3/os
Enabled:   0

Repo ID:   rhel-7-server-rpms
Repo Name: Red Hat Enterprise Linux 7 Server (RPMs)
Repo URL:  https://xxxx/pulp/repos/yyyy/DEV/zzzz/content/dist/rhel/server/7
           /$releasever/$basearch/os
Enabled:   1

Repo ID:   rh-gluster-3-client-for-rhel-7-server-rpms
Repo Name: Red Hat Storage Native Client for RHEL 7 (RPMs)
Repo URL:  https://xxxx/pulp/repos/yyyy/DEV/zzzz/content/dist/rhel/server/7
           /$releasever/$basearch/rhs-client/os
Enabled:   0

Repo ID:   rhel-7-server-rhceph-4-tools-rpms
Repo Name: Red Hat Ceph Storage Tools 4 for Red Hat Enterprise Linux 7 Server (RPMs)
Repo URL:  https://xxxx/pulp/repos/yyyy/DEV/zzzz/content/dist/rhel/server/7
           /7Server/$basearch/rhceph-tools/4/os
Enabled:   1

Repo ID:   rhel-7-server-supplementary-rpms
Repo Name: Red Hat Enterprise Linux 7 Server - Supplementary (RPMs)
Repo URL:  https://xxxx/pulp/repos/yyyy/DEV/zzzz/content/dist/rhel/server/7
           /$releasever/$basearch/supplementary/os
Enabled:   0

Repo ID:   rhel-7-server-extras-rpms
Repo Name: Red Hat Enterprise Linux 7 Server - Extras (RPMs)
Repo URL:  https://xxxx/pulp/repos/yyyy/DEV/zzzz/content/dist/rhel/server/7
           /7Server/$basearch/extras/os
Enabled:   0

Repo ID:   rhel-7-server-ansible-2.9-rpms
Repo Name: Red Hat Ansible Engine 2.9 RPMs for Red Hat Enterprise Linux 7 Server
Repo URL:  https://xxxx/pulp/repos/yyyy/DEV/zzzz/content/dist/rhel/server/7
           /7Server/$basearch/ansible/2.9/os
Enabled:   0
```

**After**

```
+----------------------------------------------------------+
    Available Repositories in /etc/yum.repos.d/redhat.repo
+----------------------------------------------------------+
Repo ID:   rhel-server-rhscl-7-rpms
Repo Name: Red Hat Software Collections RPMs for Red Hat Enterprise Linux 7 Server
Repo URL:  https://xxxx/pulp/repos/yyyy/DEV/zzzz/content/dist/rhel/server/7
           /$releasever/$basearch/rhscl/1/os
Enabled:   0

Repo ID:   rhel-7-server-dotnet-rpms
Repo Name: dotNET on RHEL RPMs for Red Hat Enterprise Linux 7 Server
Repo URL:  https://xxxx/pulp/repos/yyyy/DEV/zzzz/content/dist/rhel/server/7
           /$releasever/$basearch/dotnet/1/os
Enabled:   0

Repo ID:   rhel-7-server-satellite-client-6-rpms
Repo Name: Red Hat Satellite Client 6 (for RHEL 7 Server) (RPMs)
Repo URL:  https://xxxx/pulp/repos/yyyy/DEV/zzzz/content/dist/rhel/server/7
           /7Server/$basearch/sat-client/6/os
Enabled:   0

Repo ID:   rhel-7-server-optional-rpms
Repo Name: Red Hat Enterprise Linux 7 Server - Optional (RPMs)
Repo URL:  https://xxxx/pulp/repos/yyyy/DEV/zzzz/content/dist/rhel/server/7
           /$releasever/$basearch/optional/os
Enabled:   0

Repo ID:   rhel-7-server-rhceph-3-tools-rpms
Repo Name: Red Hat Ceph Storage Tools 3 for Red Hat Enterprise Linux 7 Server (RPMs)
Repo URL:  https://xxxx/pulp/repos/yyyy/DEV/zzzz/content/dist/rhel/server/7
           /7Server/$basearch/rhceph-tools/3/os
Enabled:   0

Repo ID:   rhel-7-server-rpms
Repo Name: Red Hat Enterprise Linux 7 Server (RPMs)
Repo URL:  https://xxxx/pulp/repos/yyyy/DEV/zzzz/content/dist/rhel/server/7
           /$releasever/$basearch/os
Enabled:   1

Repo ID:   rh-gluster-3-client-for-rhel-7-server-rpms
Repo Name: Red Hat Storage Native Client for RHEL 7 (RPMs)
Repo URL:  https://xxxx/pulp/repos/yyyy/DEV/zzzz/content/dist/rhel/server/7
           /$releasever/$basearch/rhs-client/os
Enabled:   0

Repo ID:   rhel-7-server-rhceph-4-tools-rpms
Repo Name: Red Hat Ceph Storage Tools 4 for Red Hat Enterprise Linux 7 Server (RPMs)
Repo URL:  https://xxxx/pulp/repos/yyyy/DEV/zzzz/content/dist/rhel/server/7
           /7Server/$basearch/rhceph-tools/4/os
Enabled:   0

Repo ID:   rhel-7-server-supplementary-rpms
Repo Name: Red Hat Enterprise Linux 7 Server - Supplementary (RPMs)
Repo URL:  https://xxxx/pulp/repos/yyyy/DEV/zzzz/content/dist/rhel/server/7
           /$releasever/$basearch/supplementary/os
Enabled:   0

Repo ID:   rhel-7-server-extras-rpms
Repo Name: Red Hat Enterprise Linux 7 Server - Extras (RPMs)
Repo URL:  https://xxxx/pulp/repos/yyyy/DEV/zzzz/content/dist/rhel/server/7
           /7Server/$basearch/extras/os
Enabled:   0

Repo ID:   rhel-7-server-ansible-2.9-rpms
Repo Name: Red Hat Ansible Engine 2.9 RPMs for Red Hat Enterprise Linux 7 Server
Repo URL:  https://xxxx/pulp/repos/yyyy/DEV/zzzz/content/dist/rhel/server/7
           /7Server/$basearch/ansible/2.9/os
Enabled:   0

```

**Comment by akshat87** [comment]
but I don't see it in the **yum repolist**

```
Loaded plugins: enabled_repos_upload, langpacks, package_upload, product-id, search-disabled-repos, subscription-
              : manager
repo id                                          repo name                                                     status
epel/x86_64                                      Extra Packages for Enterprise Linux 7 - x86_64                13,798
packages-microsoft-com-prod                      packages-microsoft-com-prod                                    1,726
rhel-7-server-rpms/7Server/x86_64                Red Hat Enterprise Linux 7 Server (RPMs)                      34,337
repolist: 49,861
Uploading Enabled Repositories Report
Loaded plugins: langpacks, product-id, subscription-manager
```

**Comment by jeffmcutter** [comment]
In the before state, can you try:

```
yum repolist --enablerepo rhel-7-server-extras-rpms
yum install --enablerepo rhel-7-server-extras-rpms leapp-upgrade
```

**Comment by jeffmcutter** [comment]
Is that using the same activation key as is used for satellite_activation_key_leapp?

If so, can you revert the leapp install and try running the analysis playbook?

If not, can you revert the leapp install, register to the same activation key as satellite_activation_key_leapp, and try to manually install with yum again?

**Comment by akshat87** [comment]
when we run the analysis playbook with , it gives error "Repository rhel-7-server-extras-rpms not found".

Its because analysis playbook force register without baseurl param. when we register a VM, we use below command

subscription-manager register --org=xxxx --activationkey="{{ activation_key }}" --force --serverurl=https://yyyyy --baseurl=https://yyyyy/pulp/repos

**Comment by jeffmcutter** [comment]
Hi @akshat87,

I don't understand why you would need to provide serverurl and baseurl.  katello-ca-cert should take care of that.  Do you know why?  If yes, can you please explain why.  If not, let's run one more test:

1. Revert system to pre-leapp state.
2. SSH to the system and run the below using your leapp activation_key, not including serverurl and baseurl.

```
subscription-manager register --org=xxxx --activationkey="{{ activation_key }}" --force
```

3. Try to install the leapp packages using:

```
yum install --enablerepo rhel-7-server-extras-rpms leapp-upgrade
```

4. Provide output of 1-3.

Thanks,
-Jeff

**Comment by jeffmcutter** [comment]
> Is that using the same activation key as is used for satellite_activation_key_leapp?
> 
> If so, can you revert the leapp install and try running the analysis playbook?
> 
> If not, can you revert the leapp install, register to the same activation key as satellite_activation_key_leapp, and try to manually install with yum again?

@akshat87 - Did you answer the first question?  Did you execute the respective test?

**Comment by jeffmcutter** [comment]
As katello-ca-cert is deprecated, I tried to duplicate the issue using Global Registration, but I'm unable to still.

What does your subscription-manager config show.  Can you run the following and share?

```
# subscription-manager config | egrep " hostname =| baseurl ="
   hostname = satcap1.localdomain.local
   baseurl = https://satcap1.localdomain.local/pulp/content
```

**Comment by akshat87** [comment]
it shows below

# subscription-manager config | egrep " hostname =| baseurl ="
   hostname = rhn-satellite.tools.xxx.xx.xx.xx
   baseurl = https://rhn-satellite.tools.xxx.xxx.xxx.xxx/pulp/repos

**Comment by jeffmcutter** [comment]
If it's already saved them as shown there, why do you need to pass them to subscription manager again?

**Comment by akshat87** [comment]
```
name: analysis-leapp | Register to leapp activation key
community.general.redhat_subscription:
state: present
activationkey: "{{ satellite_activation_key_leapp }}"
org_id: "{{ satellite_organization }}"
**force_register: true**
notify: Register to pre leapp activation key
when:
**leapp_upgrade_type == 'satellite'**
satellite_organization is defined
satellite_activation_key_leapp is defined
```

**Comment by jeffmcutter** [comment]
What version of Satellite are you using?

**Comment by djdanielsson** [comment]
Is this still an issue?

**Comment by bstaten** [comment]
Did this ever get solved? If so, what is the fix. I am having the same issue and using Red Hat Satellite 6.15. The upgrade type is satellite

**Comment by jeffmcutter** [comment]
Hi @bstaten,

No, it hasn't as we've not been able to replicate it.  Seems now we have 2 people with the issue though.  I am also on Sat 6.15 now.  I was wondering if it's a Global Registration issue vs. katello-ca-cert package so I tried using Global Registration and I'm still not able to replicate.  I still don't understand what the difference is.

That being said, if I create a release of infra.leapp in my own namespace on Galaxy (jeffmcutter) that includes the serverurl and baseurl parameters with a default to omit for those who don't need them, can one or both (@akshat87) of you test it to confirm it resolves the problem before I do a pull request of the same?

Thanks,
-Jeff

**Comment by bstaten** [comment]
Sorry for the late response but I was able to resolve my issue by making sure I had the RHEL 7 repositories in both the pre and post leapp content views.
