### ISSUE TITLE
Allow considering all high risk findings as inhibitors

### ISSUE THREAD

**Issue by myllynen** [redhat-cop/infra.leapp#197]
Leapp reports findings rated as high risk factor as `high (inhibitor)` and `high`. The former will prevent Leapp running while the latter won't. However, some of the latter could potentially cause notable issues under certain circumstances, such as preventing root logins making some systems inaccessible.

Now that there's a mechanism in place to ignore known inhibitors it could be helpful to optionally allow treating all high risk factor findings the same by the analysis role. This would mean that any high risk finding, unless listed as known, could be used to fail a playbook and thus forcing further investigation.

If this sounds something that could be added, on code level this should be relatively straightforward, slightly tweak filtering when parsing findings. Thanks.

**Comment by djdanielsson** [comment]
PR's welcome
