### ISSUE TITLE
Feature Request: Publish infra.leapp image on quay.io

### ISSUE THREAD

**Issue by Comnenus** [redhat-cop/infra.leapp#204]
I want to run infra.leapp (and infra.convert2rhel) using AAP, but I don't see corresponding images on https://quay.io/organization/redhat-cop.  Does an image already there work for these?  If not, it be published?

**Comment by djdanielsson** [comment]
I do not believe either collection has python requirements so there is no need for a custom EE which is why there is not one published

**Comment by djdanielsson** [comment]
if you find that one of the community upstream or supported downstream EE's are not enough feel free to reopen this explaining what is missing for which EE.
